INSERT INTO projects(funding_goal) VALUES (5);
INSERT INTO projects(funding_goal) VALUES (5);
INSERT INTO projects(funding_goal) VALUES (5);
INSERT INTO projects(funding_goal) VALUES (5);
INSERT INTO projects(funding_goal) VALUES (5);
INSERT INTO projects(funding_goal) VALUES (5);
INSERT INTO projects(funding_goal) VALUES (5);
INSERT INTO projects(funding_goal) VALUES (5);
INSERT INTO projects(funding_goal) VALUES (5);
INSERT INTO projects(funding_goal) VALUES (5);

INSERT INTO users(age) VALUES (10);
INSERT INTO users(age) VALUES (10);
INSERT INTO users(age) VALUES (10);
INSERT INTO users(age) VALUES (10);
INSERT INTO users(age) VALUES (10);
INSERT INTO users(age) VALUES (10);
INSERT INTO users(age) VALUES (10);
INSERT INTO users(age) VALUES (10);
INSERT INTO users(age) VALUES (10);
INSERT INTO users(age) VALUES (10);
INSERT INTO users(age) VALUES (10);
INSERT INTO users(age) VALUES (10);
INSERT INTO users(age) VALUES (10);
INSERT INTO users(age) VALUES (10);
INSERT INTO users(age) VALUES (10);
INSERT INTO users(age) VALUES (10);
INSERT INTO users(age) VALUES (10);
INSERT INTO users(age) VALUES (10);
INSERT INTO users(age) VALUES (10);
INSERT INTO users(age) VALUES (10);

INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);
INSERT INTO pledges(user_id, project_id, amount) VALUES (1, 2, 1);