INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project1", "cat1", 1000, 2020-05-20, 2020-06-30);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project2", "cat1", 1000, 2020-05-20, 2020-06-30);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project3", "cat1", 1000, 2020-05-20, 2020-06-30);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project4", "cat1", 1000, 2020-05-20, 2020-06-30);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project5", "cat1", 1000, 2020-05-20, 2020-06-30);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project6", "cat1", 1000, 2020-05-20, 2020-06-30);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project7", "cat1", 1000, 2020-05-20, 2020-06-30);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project8", "cat1", 1000, 2020-05-20, 2020-06-30);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project9", "cat1", 1000, 2020-05-20, 2020-06-30);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project10", "cat1", 1000, 2020-05-20, 2020-06-30);

INSERT INTO users (name, age) VALUES ("name1", 40);
INSERT INTO users (name, age) VALUES ("name2", 40);
INSERT INTO users (name, age) VALUES ("name3", 40);
INSERT INTO users (name, age) VALUES ("name4", 40);
INSERT INTO users (name, age) VALUES ("name5", 40);
INSERT INTO users (name, age) VALUES ("name6", 40);
INSERT INTO users (name, age) VALUES ("name7", 40);
INSERT INTO users (name, age) VALUES ("name1", 40);
INSERT INTO users (name, age) VALUES ("name1", 40);
INSERT INTO users (name, age) VALUES ("name1", 40);
INSERT INTO users (name, age) VALUES ("name1", 40);
INSERT INTO users (name, age) VALUES ("name1", 40);
INSERT INTO users (name, age) VALUES ("name1", 40);
INSERT INTO users (name, age) VALUES ("name1", 40);
INSERT INTO users (name, age) VALUES ("name1", 40);
INSERT INTO users (name, age) VALUES ("name1", 40);
INSERT INTO users (name, age) VALUES ("name1", 40);
INSERT INTO users (name, age) VALUES ("name1", 40);
INSERT INTO users (name, age) VALUES ("name1", 40);
INSERT INTO users (name, age) VALUES ("name1", 40);

INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 5,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 6,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 7,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 8,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 9,1);
