INSERT INTO users (name, age) VALUES ("a", 4);
INSERT INTO users (name, age) VALUES ("b", 5);
INSERT INTO users (name, age) VALUES ("c", 8);
INSERT INTO users (name, age) VALUES ("d", 9);
INSERT INTO users (name, age) VALUES ("e", 44);
INSERT INTO users (name, age) VALUES ("f", 9);
INSERT INTO users (name, age) VALUES ("g", 6);
INSERT INTO users (name, age) VALUES ("h", 2);
INSERT INTO users (name, age) VALUES ("i", 1);
INSERT INTO users (name, age) VALUES ("j", 22);
INSERT INTO users (name, age) VALUES ("k", 48);
INSERT INTO users (name, age) VALUES ("l", 32);
INSERT INTO users (name, age) VALUES ("m", 9);
INSERT INTO users (name, age) VALUES ("n", 10);
INSERT INTO users (name, age) VALUES ("o", 11);
INSERT INTO users (name, age) VALUES ("p", 41);
INSERT INTO users (name, age) VALUES ("q", 25);
INSERT INTO users (name, age) VALUES ("r", 32);
INSERT INTO users (name, age) VALUES ("s", 65);
INSERT INTO users (name, age) VALUES ("t", 96);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("apple", "tech", 1000, "July 1", "August 15");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("facebook", "tech", 2000, "July 11", "August 31");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("microsoft", "tech", 10000, "June 1", "August 1");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("twitter", "tech", 560, "July 1", "January 15");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("airbnb", "tech", 124, "March 16", "November 15");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("uber", "tech", 777, "March 1", "August 15");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("lyft", "tech", 555, "July 18", "February 15");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("allbirds", "shoes", 140, "June 3", "June 15");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("everlane", "clothes", 120, "April 1", "August 5");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("lululemon", "athletics", 1225, "June 3", "August 2");

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (222, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (222, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (222, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (222, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (187, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (187, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (187, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (187, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (827, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (827, 13, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (827, 14, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (902, 15, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (902, 16, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (902, 17, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (902, 18, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (185, 19, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (185, 20, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (185, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (871, 2, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (871, 3, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (871, 4, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (411, 5, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (411, 6, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (411, 7, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12345, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12345, 9, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (12345, 10, 10);
